[project]
name = "fju-sentiment-analysis_v1"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tasks]
# Task to start JupyterLab within the dev environment
jupyter = "jupyter lab"

[dependencies]
# Core environment dependencies (Production/Inference)
python = "3.12.13.*"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.1,<4"
scikit-learn = ">=1.8.0,<2"
scipy = ">=1.17.1,<2"
nltk = ">=3.9.3,<4"
spacy = ">=3.8.11,<4"
tqdm = ">=4.67.3,<5"
xgboost = ">=3.2.0,<4"
lightgbm = ">=4.6.0,<5"
catboost = ">=1.2.5,<2"
shap = ">=0.51.0,<0.52"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
plotly = ">=6.6.0,<7"
fsspec = ">=2026.2.0,<2027"
s3fs = ">=2026.2.0,<2027"

[pypi-dependencies]
boruta = ">=0.4.3, <0.5"

[feature.dev.dependencies]
# IDE-like features and development tools (Not for production)
jupyterlab = ">=4.5.6,<5"
jupyter-lsp = "*"
python-lsp-server = "*"
ipywidgets = ">=8.1.8,<9"
ruff = ">=0.15.5,<0.16"

[environments]
# Default environment: Only contains core ML libraries for deployment
default = ["py-deps"]
# Dev environment: Includes core libraries + IDE tools (LSP, JupyterLab, Linting)
dev = { features = ["dev"], solve_group = "default" }
